config/routes.rb
Rails.application.routes.draw do

  get "weeks/" => "weeks#index"
  get "weeks/new" => "weeks#new", as: :new_week
  get "weeks/:id" => "weeks#show", as: :week
  post "weeks/" => "weeks#create"
  get "weeks/:id/edit" => "weeks#edit", as: :edit_week
  patch "weeks/:id" => "weeks#update"

  get "users/" => "users#index"
  get "users/new" => "users#new", as: :new_user
  get "users/:id" => "users#show", as: :user
  post "users/" => "users#create"
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"

  get "events/" => "events#index"
  get "events/new" => "events#new", as: :new_event
  get "events/:id" => "events#show", as: :event
  post "events/" => "events#create"
  get "events/:id/edit" => "events#edit", as: :edit_event
  patch "events/:id" => "events#update"

end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    mount_uploader :image, ImageUploader
end

app/models/week.rb
class Week < ActiveRecord::Base 
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
    end

    def new
        @event = Event.new
    end

    def create
        @event = Event.new(params.require(:event).permit(:name, :date, :time, :location, :description, :url))

        if @event.save 
            redirect_to events_path
        else
            render :event             #if can't save to database (something goes wrong), show us that new page again.
        end 
    end # end of create method

    def edit
        @event = Event.find(params[:id])
    end

    def update
          @event = Event.find(params[:id])

        if @event.update_attributes(params.require(:event).permit(:name, :date, :time, :location, :description, :url))
            redirect_to events_path
        else
            render :edit
        end
    end

    def destroy
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(params.require(:user).permit(:name, :username, :password, :email, :is_admin, :image))

        if @user.save 
            redirect_to users_path
        else
            render :user             #if can't save to database (something goes wrong), show us that new page again.
        end 
    end # end of create method

    def edit
        @user = User.find(params[:id])

    
    end

    def update
          @user = User.find(params[:id])

        if @user.update_attributes(params.require(:user).permit(:name, :username, :password, :email, :is_admin, :image))
            redirect_to users_path
        else
            render :edit
        end
    end

    def destroy
    end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
    def index
        @weeks = Week.all
    end

    def show
        @week = Week.find(params[:id])
    end

    def new
        @week = Week.new
    end

    def create
        @week = Week.new(params.require(:week).permit(:name, :date, :message, :this_week, :next_week, :office_hours))

        if @week.save 
            redirect_to weeks_path
        else
            render :week             #if can't save to database (something goes wrong), show us that new page again.
        end 
    end # end of create method

    def edit
        @week = Week.find(params[:id])
    end

    def update
          @week = Week.find(params[:id])

        if @week.update_attributes(params.require(:week).permit(:name, :date, :this_week, :next_week, :office_hours))
            redirect_to weeks_path
        else
            render :edit
        end
    end

    def destroy
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/events/edit.html.erb
<div class="container-fluid">

<div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   

  </div>

<%= form_for @event do |f| %>

    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>

      <div>
    <%= f.label :date %>
    <%= f.date_field :date %>
    </div>

      <div>
    <%= f.label :time %>
    <%= f.time_field :time %>
    </div>

      <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
    </div>

    <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
    </div>

    

    <%= f.submit "Update Event"%>

<% end %>

</div>

app/views/events/index.html.erb
<div class="container-fluid">

  <div class="masthead">
      <h3 class="text-muted">Events</h3>   
  </div>

     <div class="jumbotron home-style">
        <% @events.each do |event| %>
            <%= link_to(event.name, event_path(event), {class:"btn btn-default", id:"user-name-button"})%>
        <% end %>

        <br>
        <%= link_to("New event", new_event_path, {class:"btn btn-primary"}) %>
    </div> 
</div>


</div>

app/views/events/new.html.erb
<div class="container-fluid">

<div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   

  </div>

<%= form_for @event do |f| %>

    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>

      <div>
    <%= f.label :date %>
    <%= f.date_field :date %>
    </div>

      <div>
    <%= f.label :time %>
    <%= f.time_field :time %>
    </div>

      <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
    </div>

    <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
    </div>

    

    <%= f.submit "Add Event"%>

<% end %>

</div>

app/views/events/show.html.erb
<div class="container-fluid">

<div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   

</div>

<%= @user.name %>
<%= @user.username %>
<%= @user.email %>
<%= @user.image %>


<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GAWeek</title>
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
  <% stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Playfair+Display' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Your Week at GA</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active">
            <li><%= link_to "Home", weeks_path %> </li>
            <li><%= link_to "Calendar of Events", weeks_path %> </li>
            <li><%= link_to "Resources", weeks_path %> </li>
            <li><%= link_to "Your Team", users_path %> </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>




<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<div class="container-fluid">

<div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   

  </div>

<%= form_for @user do |f| %>

    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>

      <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
    </div>

      <div>
    <%= f.label :email %>
    <%= f.text_area :email %>
    </div>

      <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
    </div>

    <div>
    <%= f.label :is_admin %>
    <%= f.text_field :is_admin %>
    </div>

      <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
    </div>

    <%= f.submit "Update profile"%>

<% end %>

</div>

app/views/users/index.html.erb
<div class="container-fluid">

  <div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   
  </div>

     <div class="jumbotron home-style">
        <% @users.each do |user| %>
            <%= image_tag user.image_url(:thumb) %>
             <%= link_to(user.name, user_path(user), {class:"btn btn-default", id:"user-name-button"})%>
        <% end %>

        <br>
        <%= link_to("New User", new_user_path, {class:"btn btn-primary"}) %>
    </div> 
</div>


</div>

app/views/users/new.html.erb
<div class="container-fluid">

<div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   

  </div>

<%= form_for @user, html: {multipart: true} do |f| %>

    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>

      <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
    </div>

      <div>
    <%= f.label :email %>
    <%= f.text_area :email %>
    </div>

      <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
    </div>

    <div>
    <%= f.label :is_admin %>
    <%= f.text_field :is_admin %>
    </div>

    <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
    </div>
    

    <%= f.submit "Create profile"%>

<% end %>

</div>

app/views/users/show.html.erb
<div class="container-fluid">

<div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   

</div>


<h1><%= @user.name %> </h1><br> 
<%= @user.username %> <br>
<%= @user.email %> <br>

<%= image_tag(@user.image) %>

app/views/weeks/edit.html.erb
<%= form_for @week do |f| %>

    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>

      <div>
    <%= f.label :date %>
    <%= f.text_field :date %>
    </div>

      <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
    </div>

      <div>
    <%= f.label :this_week %>
    <%= f.text_field :this_week %>
    </div>

    <div>
    <%= f.label :next_week %>
    <%= f.text_field :next_week %>
    </div>

       <div>
    <%= f.label :office_hours %>
    <%= f.text_field :office_hours %>
    </div>

    <%= f.submit "Update Week"%>

<% end %>

app/views/weeks/index.html.erb
<div class="container-fluid">

  <div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   
  </div>

     <div class="jumbotron home-style">
        <% @weeks.each do |week| %>
            <%= link_to(week.name, week_path(week), {class:"btn btn-default", id:"week-name-button"})%>

        <% end %>

        <br>
        <%= link_to("New Week", new_week_path, {class:"btn btn-primary"}) %>
    </div> 
</div>


</div>

app/views/weeks/new.html.erb
<div class="container-fluid">

<div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   

  </div>

<%= form_for @week do |f| %>

    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>

      <div>
    <%= f.label :date %>
    <%= f.text_field :date %>
    </div>

      <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
    </div>

      <div>
    <%= f.label :this_week %>
    <%= f.text_field :this_week %>
    </div>

    <div>
    <%= f.label :next_week %>
    <%= f.text_field :next_week %>
    </div>

       <div>
    <%= f.label :office_hours %>
    <%= f.text_field :office_hours %>
    </div>

    <%= f.submit "Add Week"%>

<% end %>

</div>

app/views/weeks/show.html.erb
<div class="container-fluid">

  <div class="masthead">
      <h3 class="text-muted">Your Week at GA</h3>   

  </div>

     <div class="jumbotron home-style">
        <h1> <%= @week.name %> 
        <span> <%= link_to("Edit Week", edit_week_path, {class:"btn btn-primary"}) %></span>
        </h1>
         <p class="lead" id="lead-css"><%= @week.message %> </p>
    </div> 
</div>

<div class="container">

    <div class="row" id="row-css">
            <div class="col-lg-6" id="this-week">
            <h2>This Week</h2>
              <p>  <%= @week.this_week %> </p>
            </div>

            <div class="col-lg-6" id="next-week">
              <h2>Next Week</h2>
               <p> <%= @week.next_week%></p>
           </div>
    </div>

    <div class="row">
            <div class="col-lg-4" id="office-hour">
              <h2>Office Hour</h2>
                <p><%= @week.office_hours %></p>
            </div>

              <div class="col-lg-4" id="resources">
              <h2>Resources</h2>
                <p>RESOURCES PLACEBOLDER</p>
              <p><%= link_to "See all resources", '#', class: "btn btn-primary" %></p>
            </div>

              <div class="col-lg-4" id="events">
              <h2>Events</h2>
                <p>EVENTS PLACEHOLDER</p>
              <p><%= link_to "See all Events", '#', class: "btn btn-primary" %></p>
            </div>
    </div>
</div>